// Seed data mirrors the public v31 roster. D1 is initialized from this list only when empty.
export const SEED_DOGS = [
  {name:'Dumbledore', age:'2 years', status:'Available', group:'available', image:'dumbledore.webp', blurb:'Dumbledore is currently available for pairing consideration through Golden Heart Service Dogs. Matching is based on compatibility, lifestyle, disability-related needs, temperament, and training fit.'},
  {name:'Macaroni', sex:'Male', age:'11 months', status:'Available', progress:'Level 2 Candidate • Possible Level 3', group:'available', image:'macaroni.webp', blurb:'Macaroni is currently available for pairing consideration. He is being evaluated as a Level 2 candidate with the potential for Level 3 placement depending on the handler’s needs, task requirements, and final training fit.'},
  {name:'Nala', age:'4 months', sex:'Female', status:'Available', group:'available', image:'nala.webp', blurb:'Nala is in early foundational development and evaluation as Golden Heart assesses her strengths and future service-dog fit.'},
  {name:'Nemo', age:'4 months', status:'Available', group:'available', image:'nemo.webp', blurb:'Nemo is in early foundational development and evaluation as a service-dog prospect.'},
  {name:'Mushu', age:'4 months', status:'Available', group:'available', image:'mushu.webp', blurb:'Mushu is continuing foundational training and evaluation as a service-dog prospect.'},
  {name:'Mulan', age:'4 months', status:'Available', group:'available', image:'mulan.webp', blurb:'Mulan is continuing foundational training and evaluation as a service-dog prospect.'},
  {name:'Ariel', age:'4 months', status:'Available', group:'available', image:'ariel.webp', blurb:'Ariel is continuing foundational training and evaluation as a service-dog prospect.'},

  {name:'Honey', sex:'Female', age:'7 months', status:'Pending', progress:'Status Pending', group:'pending', image:'honey.webp', specialties:['Medical Alert','Psychiatric Support'], blurb:"Honey's current status is pending. Her training focus includes medical alert and psychiatric support."},

  {name:'Oakley', breed:'Golden Retriever', sex:'Female', age:'1½ years', location:'Oklahoma', status:'Matched / In Training / Transitioning', progress:'70% through program', group:'matched', image:'oakley.webp', specialties:['Psychiatric Support','Autism Support'], blurb:'Oakley is approximately 70% through her Golden Heart program for a client in Oklahoma. Her training is focused on psychiatric support and autism support.'},
  {name:'Winston', location:'Arkansas', status:'Matched / In Training / Transitioning', group:'matched', image:'winston.webp', imageFilter:'saturate(.82) brightness(.96)', blurb:'Winston is preparing to transition into full-time placement with a client in Arkansas and is nearing graduation.'},
  {name:'Flounder', breed:'Golden Retriever', sex:'Male', age:'11 months', location:'Florida', status:'Matched / In Training / Transitioning', progress:'Midway through program', group:'matched', image:'flounder.webp', specialties:['PTSD','Psychiatric Support','Autism Support'], blurb:'Flounder is midway through his Golden Heart program for a client in Florida. His training is focused on PTSD, psychiatric support, and autism support.'},
  {name:'Max', breed:'Golden Retriever', sex:'Male', age:'1 year', location:'Connecticut', status:'Matched / In Training / Transitioning', progress:'75% through program', group:'matched', image:'max.webp', specialties:['PTSD','Psychiatric Support','Detection','Bedbug Detection','Educational Tool'], blurb:'Max is approximately 75% through his Golden Heart program. Next month, he is scheduled to transition to Connecticut full-time with his person. His training includes PTSD and psychiatric support, detection work, bedbug detection, and educational work.'},
  {name:'Liberty', breed:'Golden Retriever', sex:'Female', age:'1½ years', location:'Michigan', status:'Matched / In Training / Transitioning', progress:'Midway through program', group:'matched', image:'liberty.webp', specialties:['PTSD','Psychiatric Support','Autism Support'], blurb:'Liberty is midway through her Golden Heart program and is preparing for work with her client in Michigan. Her training is focused on PTSD, psychiatric support, and autism support.'},
  {name:'Lily', age:'8 months', location:'Oklahoma', status:'Matched / In Training / Transitioning', group:'matched', image:'lily.webp', blurb:'Lily has been paired with a client in Oklahoma and is no longer available.'},

  {name:'Theo', age:'8 months', status:'Veteran Organization Placement', group:'partner', image:'theo.webp', blurb:'Theo has been placed with a veteran organization and is no longer available through Golden Heart.'},
  {name:'Teddy', age:'8 months', status:'Veteran Organization Placement', group:'partner', image:'teddy.webp', blurb:'Teddy has been placed with a veteran organization and is no longer available through Golden Heart.'},
  {name:'Paisley', age:'1½ years', status:'Veteran Organization Placement', group:'partner', image:'paisley.webp', blurb:'Paisley has been placed with a veteran organization and is no longer available through Golden Heart.'},
  {name:'Dreamer', age:'1½ years', status:'Veteran Organization Placement', group:'partner', image:'dreamer.webp', blurb:'Dreamer has been placed with a veteran organization and is no longer available through Golden Heart.'},

  {name:'Winnie', year:'2025', status:'Graduate', group:'graduate', image:'winnie.webp', blurb:'Winnie is a 2025 Golden Heart Service Dogs graduate.'},
  {name:'Alfredo', year:'2026', status:'Graduate', group:'graduate', image:'alfredo.webp', blurb:'Alfredo is a 2026 Golden Heart Service Dogs graduate.'},
  {name:'Bear', year:'2026', status:'Graduate', group:'graduate', image:'bear.webp', blurb:'Bear is a 2026 Golden Heart Service Dogs graduate.'},
  {name:'Rango', breed:'Golden Retriever', sex:'Male', age:'1½ years', location:'Alabama', year:'2026', status:'Graduate', group:'graduate', image:'rango.webp', specialties:['PTSD','Psychiatric Support','Autism Support'], blurb:'Rango is a 2026 Golden Heart Service Dogs graduate working with his handler in Alabama. His training includes PTSD, psychiatric support, and autism support.'},
  {name:'Ruby', year:'2026', status:'Graduate', group:'graduate', veteranPlacement:true, image:'ruby.webp', blurb:'Ruby is a 2026 Golden Heart Service Dogs graduate and part of a veteran service-dog team.'},
  {name:'Whiskey', year:'2026', status:'Graduate', group:'graduate', veteranPlacement:true, image:'whiskey-current.webp', blurb:'Whiskey is a 2026 Golden Heart Service Dogs graduate and part of a veteran service-dog team.'},
  {name:'Murphy', year:'2026', status:'Graduate', group:'graduate', veteranPlacement:true, image:'murphy.webp', blurb:'Murphy is a 2026 Golden Heart Service Dogs graduate and part of a veteran service-dog team.'},
  {name:'Remington', year:'2026', status:'Graduate', group:'graduate', veteranPlacement:true, image:'remington.webp', blurb:'Remington is a 2026 Golden Heart Service Dogs graduate and part of a veteran service-dog team.'},
  {name:'Ruger', year:'2026', status:'Graduate', group:'graduate', veteranPlacement:true, image:'ruger-current.webp', blurb:'Ruger is a 2026 Golden Heart Service Dogs graduate and part of a veteran service-dog team.'}
];
